name: Build Dev

on:
  push: 
    branches: 
      - 'development',
      - 'i770-create-release'
#     branches-ignore: master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '14'

    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_DETECT_LANG_API: ${{ secrets.DETECT_LANG_API }}
        file_name: .env

    - name: Fix up git URLs
      run: echo -e '[url "https://github.com/"]\n  insteadOf = "git://github.com/"' >> ~/.gitconfig

    - name: prep build
      run: npm install && npm update && npm run update-dist 

    - name: build
      run: npm run github-build

    - name: s3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --delete
      env: 
        AWS_S3_BUCKET: 'alpheios-misc-dev'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-2'
        SOURCE_DIR: 'public'
        DEST_DIR: 'alignment-editor'

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.run_build.outputs.buildName }}
        release_name: Release ${{ steps.run_build.outputs.buildName }}
        draft: false
        prerelease: true

    - name: Upload dist
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./dist-zip/dist.zip
        asset_name: dist.zip
        asset_content_type: application/zip