name: Build Prod

on:
  push: 
    branches: 
      - 'master'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '14'

    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_API_KEY: "123456abcdef"
        file_name: .env

    - name: Show files
      run: |
        ls -a

    - name: Fix up git URLs
      run: echo -e '[url "https://github.com/"]\n  insteadOf = "git://github.com/"' >> ~/.gitconfig

    - name: build
      run: npm install && npm update && npm run build

    - name: update env
      run: bash scripts/update_env.sh ${{secrets.AUTH0_CLIENT_ID}}
      
    - name: test
      run: npm test

    - name: s3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --delete
      env: 
        AWS_S3_BUCKET: 'alpheios-alignment'
        AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_ACCESS_SECRET_KEY }}
        AWS_REGION: 'us-east-2'
        SOURCE_DIR: 'public'
