name: Build and Upload

on:
  push: 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '14'

    - name: build
      run: npm install && npm update && npm run build

    - name: s3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --delete
      env: 
        AWS_S3_BUCKET: 'alpheios-misc-dev'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-2'
        SOURCE_DIR: '.'
        DEST_DIR: 'alignment-editor/public'
    
